# Generated by Django 5.2.1 on 2025-05-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('ER', 'En ruta'), ('C', 'Completada')], default='P', max_length=20),
        ),
    ]
