# Generated by Django 5.2.1 on 2025-05-31 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tipomaterial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipomaterial',
            old_name='nombre',
            new_name='tipomat',
        ),
        migrations.AlterField(
            model_name='tipomaterial',
            name='codigo',
            field=models.CharField(choices=[('PAP', 'Papel y cartón'), ('PLAS', 'Plásticos reciclables'), ('VID', 'Vidrios'), ('LAT', 'Latas'), ('ELEC', 'Electrónicos pequeños'), ('TEX', 'Textiles'), ('VOL', 'Voluminosos reciclables')], default=None, max_length=10),
        ),
    ]
