# Generated by Django 5.2.1 on 2025-05-31 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_nombre_tipomaterial_tipomat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipomaterial',
            name='codigo',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
