# Generated by Django 5.2.1 on 2025-05-31 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_perfilusuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
