# Generated by Django 5.2.1 on 2025-05-31 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_perfilusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='puntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
