# Generated by Django 5.2.1 on 2025-05-31 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_puntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntos',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=100),
        ),
    ]
