# Generated by Django 5.2.1 on 2025-05-31 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_puntos_nombre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='puntos',
            new_name='puntitos',
        ),
    ]
