# Generated by Django 5.2.1 on 2025-05-31 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_puntos_puntitos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntitos',
            name='region',
            field=models.CharField(max_length=100),
        ),
    ]
