# Generated by Django 5.2.1 on 2025-05-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_solicitud_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='comentario',
            field=models.CharField(default='Sin comentario', max_length=100),
        ),
    ]
